Added Rma, Refund and ButtonHandling
Magenerds/mom-mock pull request #2
Opened 2018-12-13 13:33 UTC by deiserh

2018-12-13 14:16 UTC, sydekumf requested changes

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Controller/Backend/OrderController.php
> +            ->where('`order_id` = ?')
As order items are connected via foreign key to their order, via the entity id (!= increment_id), I would suggest that you also connect rma via the entity id of the order. That also saves to load the increment id here every time. Instead, I would load the order's entity id during saving the rma.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Controller/Backend/RmaController.php
> +    public function createRmaApproveAction(Request $request, Response $response)
I would call it `approveRmaAction` because you do not create anything?

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Controller/Backend/RmaController.php
> +    public function createRmaApproveAction(Request $request, Response $response)
I would call it `approveRmaAction` because you do not create anything?

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma.php
> +                '`order_id`' => "'{$this->data['order_id']}'",
Load the order's entity id here and save it instead of the increment id. That would be consistent with order items.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma/Item.php
> + * @author  Florian Sydekum <f.sydekum@techdivision.com>
Author is wrong.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma.php
> + * Class Order
`Class Order` is wrong.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma/Item.php
> + * @package MomMock\Entity\Order
`package` is wrong.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/AbstractUpdated.php
> + * @author  Harald Deiser <h.deiser@techdivision.com>
`Class` is wrong, `@package` is missing.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/AbstractUpdated.php
> +            ->from('`' . Item::TABLE_NAME . '`')
Why don't you use foreign keys with entity ids of the rma? Would be much nicer for updates/deletion in SQL.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/AbstractUpdated.php
> +    protected function setRmaStatus($rmaId)
If it says `setRmaStatus` I would expect that I can hand over the status as a parameter. This function only sets the complete status, so it should be named `setRmaCompleteStatus`. The same is true for the function below `setRmaItemStatus`.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/RefundManagement/Updated.php
> + * Class Updated
`@package` is missing.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/RefundManagement/Updated.php
> +    const REFUND_TYPE_CANCELLED = 'CANCELLED';
Why capital/lower case?

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/ReturnManagement/Authorize.php
> + * @package MomMock\Method\Sales\OrderManagement
Wrong `package`

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/ReturnManagement/Authorize.php
> +    const CREDIT_NOTE_COUNT_COLUMN = 'credit_note_counter';
Missing doc block.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/ReturnManagement/Authorize.php
> +    const CREDIT_NOTE_PREFIX = 'CDE';
If there is a const for credit note prefix, there should be a rma prefix also :-) But it is hard coded (look above)

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/ReturnManagement/Authorize.php
> +            throw new \Exception('No order data was given');
Wrong exception message.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Method/Postsales/ReturnManagement/Updated.php
> + * @author  Harald Deiser <h.deiser@techdivision.com>
Missing `package`.

2018-12-13 14:16 UTC, sydekumf commented on app/templates/methods/magento.postsales.return_management.updated.json
> +    "rma": "RMA-CS-{{rma.order_id}}-1",
`-1`, the count is hard coded?

2018-12-13 14:16 UTC, sydekumf commented on pub/web/js/buttonHandler.js
> +        message = message || "An error occure.";
`occured`

2018-12-13 14:16 UTC, sydekumf commented on setup/db.sql
> +	order_id VARCHAR(30) NOT NULL,
`order_id` is not the increment id, it is the entity id, like in order_items.

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma/Item.php
> +                '`' . self::ID_FIELD . '`' => "'{$this->data[self::ID_FIELD]}'",
You have an `ID_FIELD` which is `return_id`. In the SQL setup script you also have an `id` field. Which is correct?

2018-12-13 14:16 UTC, sydekumf commented on app/MomMock/Entity/Rma/Item.php
> +    const ID_FIELD = 'return_id';
I think this one should be only `id`. Then you also have an `rma_id` field.

2018-12-13 14:16 UTC, sydekumf commented on setup/db.sql
> +	return_id INT(6) UNSIGNED,
I would suggest `rma_id` as you call the table `rma`.

2018-12-13 14:18 UTC, sydekumf requested changes
Please see the review comments.

2018-12-17 14:28 UTC, deiserh commented on app/MomMock/Method/Postsales/RefundManagement/Updated.php
> +    const REFUND_TYPE_CANCELLED = 'CANCELLED';
both status are copied from the refund message

2018-12-17 18:24 UTC, merged